version: "3.9"
services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "financialcontrol"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    networks:
      - financial-control-network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      TZ: "America/Sao_Paulo"
    networks:
      - financial-control-network
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    restart: always

  financial-control:
    image: gbsteodoro/financial-control-rest-api:latest
    container_name: financial-control
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USERNAME: admin
      DB_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
        - financial-control-network
    depends_on:
      - postgres-db

networks:
  financial-control-network:
    driver: bridge