apiVersion: v1
kind: Service
metadata:
  name: financial-control-service
spec:
  selector:
    app: financial-control
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort
  